# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c845776e8bb92eb7778c0a6aa8a7e2b6ddeb1b706e5af7f1cd7e16776cefeea8690c39dbcec18839ba4a5e390a8c67ac9e43418d5088a23cc22b1616cc0325

test:
  secret_key_base: d1a4ecc37878b4fee8dd5bac6a6939e04f51c746be7173e820eaa79848fe5a2fb56688873080aab3237756e06ec1f55055f1f16cc62af08dc45e6bf4eb877030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
